import { Product, KeychainProduct, CaseOption } from '../types';

export const CASE_OPTIONS: CaseOption[] = [
  { id: 'clear-acrylic', name: 'Clear Acrylic', color: 'transparent', priceModifier: 0 },
  { id: 'black-leather', name: 'Black Leather', color: '#1a1a1a', priceModifier: 15 },
  { id: 'pink-glitter', name: 'Pink Glitter', color: '#ff69b4', priceModifier: 20 },
  { id: 'blue-metallic', name: 'Blue Metallic', color: '#4169e1', priceModifier: 18 },
  { id: 'no-case', name: 'No Case', color: 'none', priceModifier: -10 },
];

// Cartoonish Standard Stickers (₹10 each)
export const STANDARD_STICKERS: Product[] = [
  {
    id: 'sticker-1',
    name: 'Kawaii Cat',
    type: 'sticker',
    category: 'standard',
    price: 10,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=cat1&backgroundColor=ffd5dc,ffdfbf',
    description: 'Adorable cartoon cat with big eyes',
  },
  {
    id: 'sticker-2',
    name: 'Happy Donut',
    type: 'sticker',
    category: 'standard',
    price: 10,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=donut1&backgroundColor=ffc0cb,fff8dc',
    description: 'Smiling donut with sprinkles',
  },
  {
    id: 'sticker-3',
    name: 'Cloud Buddy',
    type: 'sticker',
    category: 'standard',
    price: 10,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=cloud1&backgroundColor=e0f7fa,b2ebf2',
    description: 'Cute cloud with a happy face',
  },
  {
    id: 'sticker-4',
    name: 'Panda Dreams',
    type: 'sticker',
    category: 'standard',
    price: 10,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=panda1&backgroundColor=f0f0f0,d0d0d0',
    description: 'Sleepy panda illustration',
  },
  {
    id: 'sticker-5',
    name: 'Rainbow Heart',
    type: 'sticker',
    category: 'standard',
    price: 10,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=heart1&backgroundColor=ffd1dc,ffe4e1',
    description: 'Colorful heart with sparkles',
  },
  {
    id: 'sticker-6',
    name: 'Star Power',
    type: 'sticker',
    category: 'standard',
    price: 10,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=star1&backgroundColor=fff59d,fff176',
    description: 'Cheerful star character',
  },
  {
    id: 'sticker-7',
    name: 'Cute Cactus',
    type: 'sticker',
    category: 'standard',
    price: 10,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=cactus1&backgroundColor=c8e6c9,a5d6a7',
    description: 'Smiling cactus in a pot',
  },
  {
    id: 'sticker-8',
    name: 'Pizza Slice',
    type: 'sticker',
    category: 'standard',
    price: 10,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=pizza1&backgroundColor=ffccbc,ffab91',
    description: 'Happy pizza slice with toppings',
  },
];

// Minecraft Stickers (₹20 each) - Official Minecraft characters and items
export const MINECRAFT_STICKERS: Product[] = [

  {
    id: 'minecraft-3',
    name: 'Villager',
    type: 'sticker',
    category: 'minecraft',
    price: 20,
    image: 'https://cdn-ai.onspace.ai/onspace/files/KS4oi3Qykj5b2WisrtwrFG/pasted-image-1765118047406-2.png',
    description: 'Trading villager with emeralds',
  },
  {
    id: 'minecraft-4',
    name: 'Alex Flying',
    type: 'sticker',
    category: 'minecraft',
    price: 20,
    image: 'https://cdn-ai.onspace.ai/onspace/files/GHPJHK3Bo5WXEsDK3piVLL/pasted-image-1765118062502-3.png',
    description: 'Alex character with elytra wings',
  },

  {
    id: 'minecraft-6',
    name: 'Steve Laughing',
    type: 'sticker',
    category: 'minecraft',
    price: 20,
    image: 'https://cdn-ai.onspace.ai/onspace/files/XTjwFjE3DCyPVL45yDrXSZ/pasted-image-1765118087286-5.png',
    description: 'Happy Steve character',
  },
  {
    id: 'minecraft-7',
    name: 'Enderman',
    type: 'sticker',
    category: 'minecraft',
    price: 20,
    image: 'https://cdn-ai.onspace.ai/onspace/files/RXZ2Jv4QEnrCKEkmhYx6zH/pasted-image-1765116603288-1.png',
    description: 'Mysterious teleporting Enderman',
  },
];

// Anime Character Stickers (₹25 each) - Real character artwork
export const ANIME_STICKERS: Product[] = [
  {
    id: 'anime-1',
    name: 'Tanjiro Kamado',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/8MHRzfJ3EqTQp4Ymqgi5Bb/pasted-image-1765088250437-0.png',
    description: 'Demon Slayer protagonist with checkered haori',
  },
  {
    id: 'anime-2',
    name: 'Naruto Uzumaki',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/nxMYRmfojssin5L8EbPsrd/pasted-image-1765102288304-0.png',
    description: 'Hokage ninja with nine-tails power and orange jumpsuit',
  },
  {
    id: 'anime-3',
    name: 'Nezuko Kamado',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/JgTWtLdtaVGCrzFbhxoGz5/ne.jpeg',
    description: 'Adorable demon sister with bamboo muzzle',
  },
  {
    id: 'anime-4',
    name: 'Monkey D. Luffy',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/naFdBBK3XimGUcUicCoNSZ/luf.jpeg',
    description: 'Straw Hat Pirate King with stretching powers',
  },
  {
    id: 'anime-5',
    name: 'Goku (Dragon Ball)',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/AEBNFozJ5ron2oGdnq98wB/go.jpeg',
    description: 'Super Saiyan warrior',
  },
  {
    id: 'anime-7',
    name: 'Kakashi Hatake',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/ZBF7VojJxfCmJTjdXdrTM/pasted-image-1765262305275-1.png',
    description: 'Copy Ninja with Sharingan eye',
  },
  {
    id: 'anime-8',
    name: 'Izuku Midoriya (Deku)',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/nCit9xSF2oDiKYZBrQsNNr/pasted-image-1765262297051-0.png',
    description: 'One For All inheritor',
  },
  {
    id: 'anime-9',
    name: 'Zenitsu Agatsuma',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/8b6H2GdZBvfgNT5XTQiTGW/pasted-image-1765262328478-3.png',
    description: 'Thunder Breathing master',
  },
  {
    id: 'anime-10',
    name: 'Eren Yeager',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/W84sYn88vMpJTHnCtFHZHQ/er.jpeg',
    description: 'Attack Titan shifter',
  },

  {
    id: 'anime-12',
    name: 'Saitama (One Punch Man)',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/bkgji7FnZEP7PhVi6eAjgW/sai.jpeg',
    description: 'Unbeatable bald hero',
  },
  {
    id: 'anime-13',
    name: 'Levi Ackerman',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/nweRSeyj6nmZB5v4tJbPvc/pasted-image-1765262339765-4.png',
    description: 'Humanity\'s strongest soldier',
  },
  {
    id: 'anime-14',
    name: 'Vegeta',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/PFRLHXrYHFBaxCTjdXdrTM/pasted-image-1765262315988-2.png',
    description: 'Saiyan prince',
  },
  {
    id: 'anime-15',
    name: 'Satoru Gojo',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/XSoZFQmbtsaZuQoV7cMkp2/pasted-image-1765102302804-1.png',
    description: 'Jujutsu Kaisen\'s strongest sorcerer with Six Eyes',
  },



  {
    id: 'anime-21',
    name: 'Sasuke',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/NZJ9TGbEWDoewzmUvFsdq7/pasted-image-1765116585563-0.jpeg',
    description: 'Uchiha Sasuke in Minecraft pixel art style',
  },

  {
    id: 'anime-23',
    name: 'Roronoa Zoro',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/BVyucE6xXp56RSoTKKcgxt/pasted-image-1765116613530-2.png',
    description: 'Three-sword style master from One Piece',
  },
  {
    id: 'anime-24',
    name: 'Luffy',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/6z3Z5BvnYMDo9xsJQZZcSX/pasted-image-1765116634172-4.png',
    description: 'Captain Luffy Straw Hat Pirates from One Piece',
  },
  {
    id: 'anime-25',
    name: 'Chopper',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/H67fXYQSi6GG77PnJBukZH/pasted-image-1765116645264-5.png',
    description: 'Adorable doctor Tony Tony Chopper from One Piece',
  },
  {
    id: 'anime-26',
    name: 'Nami',
    type: 'sticker',
    category: 'anime',
    price: 25,
    image: 'https://cdn-ai.onspace.ai/onspace/files/UpmuRqf2jgMmTv5uGYVavD/pasted-image-1765116625105-3.png',
    description: 'Navigator Nami from One Piece',
  },
];

// Anime Keychains (₹110 each) - Real character artwork
export const ANIME_KEYCHAINS: KeychainProduct[] = [
  {
    id: 'keychain-anime-1',
    name: 'Tanjiro Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/8MHRzfJ3EqTQp4Ymqgi5Bb/pasted-image-1765088250437-0.png',
    description: 'Premium Tanjiro acrylic keychain with checkered pattern',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-anime-2',
    name: 'Naruto Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/nxMYRmfojssin5L8EbPsrd/pasted-image-1765102288304-0.png',
    description: 'Premium Naruto acrylic keychain with headband',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-anime-3',
    name: 'Nezuko Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/JgTWtLdtaVGCrzFbhxoGz5/ne.jpeg',
    description: 'Premium Nezuko acrylic keychain with bamboo',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-anime-4',
    name: 'Luffy Straw Hat Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/naFdBBK3XimGUcUicCoNSZ/luf.jpeg',
    description: 'Premium Luffy acrylic keychain with iconic straw hat',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-anime-5',
    name: 'Goku Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/AEBNFozJ5ron2oGdnq98wB/go.jpeg',
    description: 'Premium Goku acrylic keychain in Super Saiyan form',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-anime-7',
    name: 'Levi Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/nweRSeyj6nmZB5v4tJbPvc/pasted-image-1765262339765-4.png',
    description: 'Premium Levi acrylic keychain with ODM gear',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-anime-8',
    name: 'Satoru Gojo Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/XSoZFQmbtsaZuQoV7cMkp2/pasted-image-1765102302804-1.png',
    description: 'Premium Gojo acrylic keychain with Six Eyes design',
    caseOptions: CASE_OPTIONS,
  },

];

// Food & Cute Keychains (₹110 each)
export const FOOD_KEYCHAINS: KeychainProduct[] = [
  {
    id: 'keychain-food-1',
    name: 'Boba Tea Keychain',
    type: 'keychain',
    category: 'food',
    price: 110,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=boba&backgroundColor=d4a373,8b4513',
    description: 'Cute bubble tea charm',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-food-2',
    name: 'Sushi Roll Keychain',
    type: 'keychain',
    category: 'food',
    price: 110,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=sushi&backgroundColor=ff6b6b,ee5a6f',
    description: 'Kawaii sushi roll',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-food-3',
    name: 'Cupcake Keychain',
    type: 'keychain',
    category: 'food',
    price: 110,
    image: 'https://api.dicebear.com/7.x/bottts/svg?seed=cupcake&backgroundColor=ffb3ba,ffdfba',
    description: 'Sweet cupcake charm',
    caseOptions: CASE_OPTIONS,
  },
];

// Minimalist Keychains (₹110 each)
export const MINIMALIST_KEYCHAINS: KeychainProduct[] = [
  {
    id: 'keychain-min-1',
    name: 'Geometric Moon',
    type: 'keychain',
    category: 'minimalist',
    price: 110,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=moon&backgroundColor=2c3e50',
    description: 'Minimal moon design',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-min-2',
    name: 'Mountain Peak',
    type: 'keychain',
    category: 'minimalist',
    price: 110,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=mountain&backgroundColor=34495e',
    description: 'Simple mountain silhouette',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-min-3',
    name: 'Wave Pattern',
    type: 'keychain',
    category: 'minimalist',
    price: 110,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=wave&backgroundColor=3498db',
    description: 'Ocean wave minimal art',
    caseOptions: CASE_OPTIONS,
  },
];

// Gaming Keychains (₹110 each)
export const GAMING_KEYCHAINS: KeychainProduct[] = [
  {
    id: 'keychain-game-1',
    name: 'Pixel Sword',
    type: 'keychain',
    category: 'gaming',
    price: 110,
    image: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=sword&backgroundColor=9b59b6',
    description: '8-bit sword charm',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-game-2',
    name: 'Controller Icon',
    type: 'keychain',
    category: 'gaming',
    price: 110,
    image: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=controller&backgroundColor=e74c3c',
    description: 'Retro game controller',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-game-3',
    name: 'Pixel Heart',
    type: 'keychain',
    category: 'gaming',
    price: 110,
    image: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=heart&backgroundColor=e91e63',
    description: 'HP heart from games',
    caseOptions: CASE_OPTIONS,
  },


  {
    id: 'keychain-game-8',
    name: 'Zoro Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/BVyucE6xXp56RSoTKKcgxt/pasted-image-1765116613530-2.png',
    description: 'Roronoa Zoro swordsman keychain from One Piece',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-game-9',
    name: 'Nami Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/6z3Z5BvnYMDo9xsJQZZcSX/pasted-image-1765116634172-4.png',
    description: 'Nami navigator keychain from One Piece',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-game-10',
    name: 'Chopper Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/UpmuRqf2jgMmTv5uGYVavD/pasted-image-1765116625105-3.png',
    description: 'Tony Tony Chopper cute doctor keychain from One Piece',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-game-11',
    name: 'Enderman Keychain',
    type: 'keychain',
    category: 'gaming',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/RXZ2Jv4QEnrCKEkmhYx6zH/pasted-image-1765116603288-1.png',
    description: 'Minecraft Enderman teleporting mob keychain',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'keychain-game-12',
    name: 'Sasuke Keychain',
    type: 'keychain',
    category: 'anime',
    price: 110,
    image: 'https://cdn-ai.onspace.ai/onspace/files/NZJ9TGbEWDoewzmUvFsdq7/pasted-image-1765116585563-0.jpeg',
    description: 'Sasuke Uchiha in Minecraft pixel art keychain',
    caseOptions: CASE_OPTIONS,
  },
];

// Premium Exclusive Stickers (₹35 each) - Only for premium members
export const PREMIUM_STICKERS: Product[] = [
  {
    id: 'premium-sticker-1',
    name: 'Limited Edition Gold Tanjiro',
    type: 'sticker',
    category: 'anime',
    price: 35,
    image: 'https://cdn-ai.onspace.ai/onspace/files/8MHRzfJ3EqTQp4Ymqgi5Bb/pasted-image-1765088250437-0.png',
    description: '✨ PREMIUM EXCLUSIVE - Holographic gold foil sticker',
  },
  {
    id: 'premium-sticker-2',
    name: 'Exclusive Naruto Rasengan',
    type: 'sticker',
    category: 'anime',
    price: 35,
    image: 'https://cdn-ai.onspace.ai/onspace/files/nxMYRmfojssin5L8EbPsrd/pasted-image-1765102288304-0.png',
    description: '✨ PREMIUM EXCLUSIVE - Glow-in-the-dark effect',
  },
  {
    id: 'premium-sticker-3',
    name: 'Diamond Luffy Gear 5',
    type: 'sticker',
    category: 'anime',
    price: 35,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&h=400&fit=crop',
    description: '✨ PREMIUM EXCLUSIVE - Metallic diamond finish',
  },
  {
    id: 'premium-sticker-4',
    name: 'Holographic Gojo Satoru',
    type: 'sticker',
    category: 'anime',
    price: 35,
    image: 'https://cdn-ai.onspace.ai/onspace/files/XSoZFQmbtsaZuQoV7cMkp2/pasted-image-1765102302804-1.png',
    description: '✨ PREMIUM EXCLUSIVE - Rainbow holographic sticker with Six Eyes',
  },
];

// Premium Exclusive Keychains (₹150 each) - Only for premium members
export const PREMIUM_KEYCHAINS: KeychainProduct[] = [
  {
    id: 'premium-keychain-1',
    name: 'Limited Edition Tanjiro Metal Keychain',
    type: 'keychain',
    category: 'anime',
    price: 150,
    image: 'https://cdn-ai.onspace.ai/onspace/files/8MHRzfJ3EqTQp4Ymqgi5Bb/pasted-image-1765088250437-0.png',
    description: '✨ PREMIUM EXCLUSIVE - High-quality metal with LED light',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'premium-keychain-2',
    name: 'Exclusive Goku Super Saiyan Keychain',
    type: 'keychain',
    category: 'anime',
    price: 150,
    image: 'https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=400&h=400&fit=crop',
    description: '✨ PREMIUM EXCLUSIVE - 3D sculpted metal with glow effect',
    caseOptions: CASE_OPTIONS,
  },
  {
    id: 'premium-keychain-3',
    name: 'Diamond Edition Naruto Keychain',
    type: 'keychain',
    category: 'anime',
    price: 150,
    image: 'https://cdn-ai.onspace.ai/onspace/files/nxMYRmfojssin5L8EbPsrd/pasted-image-1765102288304-0.png',
    description: '✨ PREMIUM EXCLUSIVE - Crystal embedded premium metal',
    caseOptions: CASE_OPTIONS,
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...STANDARD_STICKERS,
  ...MINECRAFT_STICKERS,
  ...ANIME_STICKERS,
  ...ANIME_KEYCHAINS,
  ...FOOD_KEYCHAINS,
  ...MINIMALIST_KEYCHAINS,
  ...GAMING_KEYCHAINS,
];

export const ALL_PREMIUM_PRODUCTS: Product[] = [
  ...PREMIUM_STICKERS,
  ...PREMIUM_KEYCHAINS,
];

export const ALL_KEYCHAINS: KeychainProduct[] = [
  ...ANIME_KEYCHAINS,
  ...FOOD_KEYCHAINS,
  ...MINIMALIST_KEYCHAINS,
  ...GAMING_KEYCHAINS,
];
